/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.carshop.application;

import ca.mcgill.ecse.carshop.model.CarShop;
import ca.mcgill.ecse.carshop.model.User;

public class CarShopApplication {
	
	private static CarShop carShop;
	
	//currentuser field with set and getter
	/*
	 * Author Simo Benkirane
	 */
	static User currentuser = null;
	
	/*
	 * Author Simo Benkirane
	 */
	public static User getCurrentUser() {
		return currentuser;
	}
	
	
	/*
	 * Author Simo Benkirane
	 */
	public static void setCurrentUser(User user) {
		currentuser = user;
	}
	
	public static void logoutCurrentUser(User user) {
		currentuser = null;
	}
	
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new CarShopApplication().getGreeting());
    }
    
    public static CarShop getCarShop() {
    	if (carShop == null)
    		carShop = new CarShop();
    	return carShop;
    }
}
